"""pyawe — Python client library for the AWE (Advanced Workflow Engine) API."""

from .client import AweClient
from .exceptions import (
    AweAuthError,
    AweError,
    AweNotFoundError,
    AweServerError,
    AweValidationError,
)
from .models import (
    BranchTaskResult,
    ChatMessage,
    ChatSession,
    CheckpointCheck,
    CheckpointCheckRun,
    CheckpointCheckScript,
    Connection,
    ConnectionTestResult,
    CreateLoopBlockResponse,
    DataBinding,
    ExecutionProfile,
    InstantiateWorkItemResponse,
    Job,
    JobWithWorkflows,
    LoginInfo,
    LoopBlock,
    LoopType,
    PassthroughCheckpoints,
    PortDirection,
    PortValueType,
    Project,
    ProjectWithJobs,
    ResolvedConnection,
    ScheduledScript,
    ScheduledScriptDispatch,
    ScheduledScriptRun,
    ScheduleStatus,
    ScriptType,
    Status,
    Task,
    TaskLink,
    TaskPortSpec,
    TaskPortValues,
    TaskRun,
    TaskScript,
    TaskStateHistoryEntry,
    TaskTeamRole,
    TaskType,
    TaskWithContext,
    Workflow,
    WorkflowAllocation,
    WorkflowWithTasks,
    WorkItem,
    WorkItemBranch,
    WorkItemCheck,
    WorkItemCheckScript,
    WorkItemPortSpec,
    WorkItemScript,
    WorkItemTeamRole,
)

__all__ = [
    # Client
    "AweClient",
    # Exceptions
    "AweError",
    "AweAuthError",
    "AweNotFoundError",
    "AweValidationError",
    "AweServerError",
    # Enumerations
    "Status",
    "ScheduleStatus",
    "TaskType",
    "PortDirection",
    "PortValueType",
    "ScriptType",
    "LoopType",
    # Models
    "LoginInfo",
    "Workflow",
    "WorkflowWithTasks",
    "WorkflowAllocation",
    "Task",
    "TaskWithContext",
    "TaskLink",
    "TaskPortSpec",
    "TaskPortValues",
    "DataBinding",
    "TaskScript",
    "TaskRun",
    "TaskTeamRole",
    "Job",
    "JobWithWorkflows",
    "Project",
    "ProjectWithJobs",
    "ExecutionProfile",
    "LoopBlock",
    "CreateLoopBlockResponse",
    "TaskStateHistoryEntry",
    # Connections
    "Connection",
    "ConnectionTestResult",
    "ResolvedConnection",
    # Work items
    "WorkItem",
    "WorkItemPortSpec",
    "WorkItemScript",
    "WorkItemCheck",
    "WorkItemCheckScript",
    "WorkItemTeamRole",
    "WorkItemBranch",
    "BranchTaskResult",
    "InstantiateWorkItemResponse",
    # Checkpoint checks
    "CheckpointCheck",
    "CheckpointCheckScript",
    "CheckpointCheckRun",
    "PassthroughCheckpoints",
    # Scheduled scripts
    "ScheduledScript",
    "ScheduledScriptRun",
    "ScheduledScriptDispatch",
    # AI chat sessions
    "ChatSession",
    "ChatMessage",
]
